/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AnaliticaRouteImport } from './routes/analitica'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as PrediccionRouteImport } from './routes/prediccion'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ReposicionRouteImport } from './routes/reposicion'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosSkuRouteImport } from './routes/productos.$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaRoute = AnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const PrediccionRoute = PrediccionRouteImport.update({
  id: '/prediccion',
  path: '/prediccion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposicionRoute = ReposicionRouteImport.update({
  id: '/reposicion',
  path: '/reposicion',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSkuRoute = ProductosSkuRouteImport.update({
  id: '/productos/$sku',
  path: '/productos/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/analitica': typeof AnaliticaRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/prediccion': typeof PrediccionRoute
  '/reportes': typeof ReportesRoute
  '/reposicion': typeof ReposicionRoute
  '/simulador': typeof SimuladorRoute
  '/productos/$sku': typeof ProductosSkuRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/analitica': typeof AnaliticaRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/prediccion': typeof PrediccionRoute
  '/reportes': typeof ReportesRoute
  '/reposicion': typeof ReposicionRoute
  '/simulador': typeof SimuladorRoute
  '/productos/$sku': typeof ProductosSkuRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/analitica': typeof AnaliticaRoute
  '/historial': typeof HistorialRoute
  '/inventario': typeof InventarioRoute
  '/prediccion': typeof PrediccionRoute
  '/reportes': typeof ReportesRoute
  '/reposicion': typeof ReposicionRoute
  '/simulador': typeof SimuladorRoute
  '/productos/$sku': typeof ProductosSkuRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/analitica'
    | '/historial'
    | '/inventario'
    | '/prediccion'
    | '/reportes'
    | '/reposicion'
    | '/simulador'
    | '/productos/$sku'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/analitica'
    | '/historial'
    | '/inventario'
    | '/prediccion'
    | '/reportes'
    | '/reposicion'
    | '/simulador'
    | '/productos/$sku'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/analitica'
    | '/historial'
    | '/inventario'
    | '/prediccion'
    | '/reportes'
    | '/reposicion'
    | '/simulador'
    | '/productos/$sku'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  AnaliticaRoute: typeof AnaliticaRoute
  HistorialRoute: typeof HistorialRoute
  InventarioRoute: typeof InventarioRoute
  PrediccionRoute: typeof PrediccionRoute
  ReportesRoute: typeof ReportesRoute
  ReposicionRoute: typeof ReposicionRoute
  SimuladorRoute: typeof SimuladorRoute
  ProductosSkuRoute: typeof ProductosSkuRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica': {
      id: '/analitica'
      path: '/analitica'
      fullPath: '/analitica'
      preLoaderRoute: typeof AnaliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediccion': {
      id: '/prediccion'
      path: '/prediccion'
      fullPath: '/prediccion'
      preLoaderRoute: typeof PrediccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reposicion': {
      id: '/reposicion'
      path: '/reposicion'
      fullPath: '/reposicion'
      preLoaderRoute: typeof ReposicionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$sku': {
      id: '/productos/$sku'
      path: '/productos/$sku'
      fullPath: '/productos/$sku'
      preLoaderRoute: typeof ProductosSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  AnaliticaRoute: AnaliticaRoute,
  HistorialRoute: HistorialRoute,
  InventarioRoute: InventarioRoute,
  PrediccionRoute: PrediccionRoute,
  ReportesRoute: ReportesRoute,
  ReposicionRoute: ReposicionRoute,
  SimuladorRoute: SimuladorRoute,
  ProductosSkuRoute: ProductosSkuRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
